const songs = [
  {
    name: "OK",
    artist: "Culture Jam ft Bramsito, Frenna",
    year: 2022,
    duration: 2.36,
  },
  {
    name: "Favorite Girl",
    artist: "Priceless",
    year: 2021,
    duration: 2.51,
  },
  {
    name: "7 Dagen",
    artist: "Architrackz",
    year: 2022,
    duration: 3.15,
  },
  {
    name: "Karma",
    artist: "Architrackz ft. KATNUF",
    year: 2024,
    duration: 2.52,
  },
  {
    name: "Lost & Found",
    artist: "Broederliefde",
    year: 2024,
    duration: 3.16,
  },
  {
    name: "After Six",
    artist: "Broederliefde ft. Antoon, Ronnie Flex",
    year: 2024,
    duration: 2.46,
  },
  {
    name: "Guap",
    artist: "Bryan MG & Architrackz",
    year: 2023,
    duration: 2.41,
  },
  {
    name: "Big 7",
    artist: "Burna Boy",
    year: 2023,
    duration: 2.31,
  },
  {
    name: "Dumlla Dumlla",
    artist: "Dafina Zeqiri & DYSTINCT",
    year: 2024,
    duration: 3.07,
  },
  {
    name: "Geen Reden",
    artist: "Delany ft. Yxng Le",
    year: 2024,
    duration: 2.56,
  },
  {
    name: "679",
    artist: "Fetty Wap ft. Monty",
    year: 2015,
    duration: 3.11,
  },
  {
    name: "Girls Wanna Have Fun",
    artist: "Frenna",
    year: 2024,
    duration: 3.29,
  },
  {
    name: "Maradona",
    artist: "Frenna",
    year: 2024,
    duration: 2.26,
  },
  {
    name: "Nog Steeds",
    artist: "Jayh",
    year: 2024,
    duration: 3.18,
  },
  {
    name: "Tyar En Waka",
    artist: "Jonna Fraser",
    year: 2024,
    duration: 2.41,
  },
  {
    name: "I Need Your Love",
    artist: "Jonna Fraser x Frenna x Yam",
    year: 2024,
    duration: 2.44,
  },
  {
    name: "Berichten",
    artist: "Kleine John",
    year: 2024,
    duration: 2.08,
  },
  {
    name: "Nog Steeds",
    artist: "KM x Lijpe",
    year: 2023,
    duration: 2.46,
  },
  {
    name: "Camera",
    artist: "Bryan MG ft. MB, Tawsen",
    year: 2024,
    duration: 2.58,
  },
  {
    name: "Guatauba",
    artist: "Plan B",
    year: 2002,
    duration: 2.44,
  },
  {
    name: "Carita de Inocente",
    artist: "Prince Royce",
    year: 2020,
    duration: 3.10,
  },
  {
    name: "Rechazame",
    artist: "Prince Royce",
    year: 2010,
    duration: 3.45,
  },
  {
    name: "Xtra Cool",
    artist: "Young John",
    year: 2022,
    duration: 5.14,
  },
  {
    name: "Yo Voy",
    artist: "Zion & Lennox ft. Daddy Yankee",
    year: 2004,
    duration: 3.51,
  },
  {
    name: "WINE",
    artist: "B Young",
    year: 2020,
    duration: 5.48,
  },
  {
    name: "Anders Doet",
    artist: "Architrackz ft. Jayh",
    year: 2022,
    duration: 5.39,
  },
  {
    name: "Trop Parler",
    artist: "Franglish",
    year: 2023,
    duration: 3.04,
  },
  {
    name: "El Clásico",
    artist: "Lijpe ft. Frenna",
    year: 2022,
    duration: 2.40,
  },
  {
    name: "Hurtin me",
    artist: "Stefflon Don ft. French Montana",
    year: 2017,
    duration: 3.34,
  },
  {
    name: "Sans Effet",
    artist: "Tayc",
    year: 2022,
    duration: 5.21,
  },
  {
    name: "Essence",
    artist: "Wizkid ft. Tems",
    year: 2020,
    duration: 4.05,
  },
  {
    name: "Validée",
    artist: "Booba ft. Benash",
    year: 2015,
    duration: 3.26,
  },
  {
    name: "African Queen",
    artist: "KM ft. Bryan MG",
    year: 2020,
    duration: 2.59,
  },
  {
    name: "Envy Us",
    artist: "Stefflon Don ft. Abra Cadabra",
    year: 2016,
    duration: 3.48,
  },
  {
    name: "Carlo Colucci",
    artist: "Driess",
    year: 2019,
    duration: 2.20,
  },
  {
    name: "Pantat",
    artist: "Kimberlee Ramirez ft. BD, JPB",
    year: 2021,
    duration: 2.19,
  },
  {
    name: "Leven",
    artist: "Jack ft. Ashafar",
    year: 2019,
    duration: 2.09,
  }
];

export default songs;